wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712793887.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.0
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
classifier_attention_resolutions:
  desc: null
  value: 16,8
classifier_depth:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.0042461596457198485
weight_decay:
  desc: null
  value: 0.05
